/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ex01.Ex01;
import ex02.Ex02;
import ex03.Ex03;
import ex05.PersistenciaFormas;
import ex05.Circulo;
import ex05.Forma;
import ex05.Retangulo;
import ex05.Triangulo;
import java.io.FileNotFoundException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import util.FileChooser;

/**
 *
 * @author vinic
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private Path ultimoArquivoCriado = null;
    private String caminhoAnterior;
    private ArrayList<Forma> formas = new ArrayList();
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        this.setResizable(false);
        this.setAlwaysOnTop(true);
        //this.setSize(Toolkit.getDefaultToolkit().getScreenSize().width, 68);
        this.setSize(503, 68);
        this.setLocation(0, 0);
        this.setTitle("Lista 1");
        
        ex01.setTitle("Questão 01");
        ex01.setSize(320, 200);
        ex01.setResizable(false);
    
        ex02.setSize(542, 100);
        ex02.setTitle("Questão 02");
        ex02.setResizable(false);
        
        ex03.setTitle("Questão 03");
        ex03.setSize(427, 306);
        ex03.setResizable(false);
        
        ex04.setSize(600, 400);
        ex04.setTitle("Questão 04");
        ex04.setResizable(false);
        
        ex05.setSize(345, 300);
        ex05.setTitle("Questão 05");
        ex05.setResizable(false);
        
        jTextField1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ex01 = new javax.swing.JFrame();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        ex02 = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        textFieldCaminho = new javax.swing.JTextField();
        btnCript = new javax.swing.JButton();
        textFieldNumero = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ex03 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taArqEntrada = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        ex04 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        ex05 = new javax.swing.JFrame();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jSpinner8 = new javax.swing.JSpinner();
        jScrollPane5 = new javax.swing.JScrollPane();
        taFormas = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSpinner9 = new javax.swing.JSpinner();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jSpinner10 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jSpinner11 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSpinner12 = new javax.swing.JSpinner();
        jSpinner13 = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSpinner14 = new javax.swing.JSpinner();
        jButton22 = new javax.swing.JButton();
        btnEx02 = new javax.swing.JButton();
        btnEx01 = new javax.swing.JButton();
        btnEx3 = new javax.swing.JButton();
        btnEx4 = new javax.swing.JButton();
        btnEx5 = new javax.swing.JButton();

        jButton4.setText("Criar Arquivo de Texto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Criar Arquivo Binário");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        areaTexto.setEditable(false);
        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        javax.swing.GroupLayout ex01Layout = new javax.swing.GroupLayout(ex01.getContentPane());
        ex01.getContentPane().setLayout(ex01Layout);
        ex01Layout.setHorizontalGroup(
            ex01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ex01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ex01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(ex01Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ex01Layout.setVerticalGroup(
            ex01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ex01Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ex01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );

        ex02.setResizable(false);

        jButton1.setText("Procurar Arquivo de Texto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textFieldCaminho.setEditable(false);

        btnCript.setText("Criptografar");
        btnCript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriptActionPerformed(evt);
            }
        });

        textFieldNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jButton2.setText("Abrir Arquivo de Saída");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Abrir Diretório do Arquivo de Saída");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ex02Layout = new javax.swing.GroupLayout(ex02.getContentPane());
        ex02.getContentPane().setLayout(ex02Layout);
        ex02Layout.setHorizontalGroup(
            ex02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ex02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ex02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ex02Layout.createSequentialGroup()
                        .addComponent(textFieldCaminho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(ex02Layout.createSequentialGroup()
                        .addComponent(textFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCript)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ex02Layout.setVerticalGroup(
            ex02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ex02Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ex02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(textFieldCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ex02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCript)
                    .addComponent(textFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        taArqEntrada.setEditable(false);
        taArqEntrada.setColumns(20);
        taArqEntrada.setRows(5);
        jScrollPane2.setViewportView(taArqEntrada);

        jTextField1.setEditable(false);

        jButton6.setText("Abir Arquivo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Atualizar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Editar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton12.setText("Salvar Como");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Salvar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Arquivo de Entrada", jPanel1);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jButton9.setText("Gerar Arquivo de Saída");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Abir Local do Arquivo");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Arquivo de Saída", jPanel2);

        javax.swing.GroupLayout ex03Layout = new javax.swing.GroupLayout(ex03.getContentPane());
        ex03.getContentPane().setLayout(ex03Layout);
        ex03Layout.setHorizontalGroup(
            ex03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        ex03Layout.setVerticalGroup(
            ex03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jLabel2.setText("ex04");

        javax.swing.GroupLayout ex04Layout = new javax.swing.GroupLayout(ex04.getContentPane());
        ex04.getContentPane().setLayout(ex04Layout);
        ex04Layout.setHorizontalGroup(
            ex04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ex04Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel2)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        ex04Layout.setVerticalGroup(
            ex04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ex04Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(112, 112, 112))
        );

        jButton16.setText("Atualizar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton19.setText("Remover");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        taFormas.setEditable(false);
        taFormas.setColumns(20);
        taFormas.setRows(5);
        jScrollPane5.setViewportView(taFormas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton16)
                    .addComponent(jButton19)
                    .addComponent(jSpinner8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Vizualizar Objetos", jPanel3);

        jLabel8.setText("Raio:");

        jButton20.setText("Criar Círculo");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setText("Criar Retângulo");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jLabel9.setText("Altura:");

        jLabel10.setText("Lado:");

        jLabel11.setText("Lado 1:");

        jLabel12.setText("Lado 2:");

        jLabel13.setText("Lado 3:");

        jButton22.setText("Criar Triângulo");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jSpinner12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner14))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSpinner9, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jSpinner11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSpinner10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(33, 33, 33)
                                    .addComponent(jLabel12)
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel13))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 5, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Cadastrar Objetos", jPanel4);

        javax.swing.GroupLayout ex05Layout = new javax.swing.GroupLayout(ex05.getContentPane());
        ex05.getContentPane().setLayout(ex05Layout);
        ex05Layout.setHorizontalGroup(
            ex05Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        ex05Layout.setVerticalGroup(
            ex05Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEx02.setText("Questão 02");
        btnEx02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx02ActionPerformed(evt);
            }
        });

        btnEx01.setText("Questão 01");
        btnEx01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx01ActionPerformed(evt);
            }
        });

        btnEx3.setText("Questão 03");
        btnEx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx3ActionPerformed(evt);
            }
        });

        btnEx4.setText("Questão 04");
        btnEx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx4ActionPerformed(evt);
            }
        });

        btnEx5.setText("Questão 05");
        btnEx5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEx5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEx01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEx02)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEx3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEx4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEx5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEx02)
                    .addComponent(btnEx01)
                    .addComponent(btnEx3)
                    .addComponent(btnEx4)
                    .addComponent(btnEx5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEx02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx02ActionPerformed
        setTela(ex02);
    }//GEN-LAST:event_btnEx02ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Ex02.abreFileChooser(textFieldCaminho, ex02);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriptActionPerformed
        
        try {
            ultimoArquivoCriado = Ex02.resolucao(textFieldCaminho, textFieldNumero);
        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(ex02, iae.getMessage());
        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(ex02, "Problema na leitura do arquivo:\n" + ioe.getMessage());
        }
        
        
    }//GEN-LAST:event_btnCriptActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try {
            Runtime.getRuntime().exec("explorer C:\\Users\\vinic\\Desktop\\Projetos no NetBeans\\Lista1\\src\\ex02");
        } catch (IOException ex) {
            //Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(ex02, "Problema ao abrir diretório:\n" + ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Runtime.getRuntime().exec("explorer " + ultimoArquivoCriado);
        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(ex02, "Ocorreu um problema na hora de abir o arquivo: " + ioe.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnEx01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx01ActionPerformed
        setTela(ex01);
    }//GEN-LAST:event_btnEx01ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        try {
            Ex01.arqTexto(areaTexto);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(ex01, "Ocorreu um  erro na hora de criar o arquivo:\n" + ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        try {
            Ex01.arqBinario(areaTexto);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(ex01, "Ocorreu um  erro na hora de criar o arquivo:\n" + ex.getLocalizedMessage());
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnEx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx3ActionPerformed
        setTela(ex03);
    }//GEN-LAST:event_btnEx3ActionPerformed

    private void btnEx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx4ActionPerformed
        setTela(ex04);
    }//GEN-LAST:event_btnEx4ActionPerformed

    private void btnEx5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEx5ActionPerformed
        setTela(ex05);
    }//GEN-LAST:event_btnEx5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        caminhoAnterior = jTextField1.getText();
        jTextField1.setText
               (FileChooser.open(ex03, 
                Paths.get("src\\util").toAbsolutePath().toString(), 
                "Procurar Arquivos", 
                "Arquivos de Texto", 
                new String[]{"txt"}, 
                JFileChooser.FILES_ONLY));
        setTAArqEntrada();
        taArqEntrada.setEditable(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        setTAArqEntrada();
        taArqEntrada.setEditable(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        taArqEntrada.setEditable(true);
        taArqEntrada.requestFocus();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
        caminhoAnterior = jTextField1.getText();
        String p = FileChooser.open(ex03, 
                Paths.get("src\\util").toAbsolutePath().toString(), 
                "Salvar Como", 
                "Arquivo de Texto", 
                new String[] {"txt"}, 
                "Salvar",
                JFileChooser.FILES_ONLY);
        jTextField1.setText(p + ".txt");
        try{
            if(jTextField1.getText().equals("null.txt")) { throw new IllegalArgumentException(); }
            Ex03.salvarArquivo(jTextField1.getText(), taArqEntrada.getText());
        } catch(IOException ioe) {
            JOptionPane.showMessageDialog(ex03, "Ocorreu um erro " + ioe.getMessage());
        } catch(IllegalArgumentException iae) {
            jTextField1.setText(caminhoAnterior);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(ex03, "oiee");
        }
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if(!jTextField1.getText().equals("")) {
            try{
                Ex03.salvarArquivo(jTextField1.getText(), taArqEntrada.getText());
            } catch(FileNotFoundException fnfe) {
                JOptionPane.showMessageDialog(null, "Arquivo não encontrado:\n" + fnfe.getMessage());
                jTextField1.setText(caminhoAnterior);
            } catch(IOException ioe) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro na hora de abir o arquivo:\n" + ioe.getMessage());
                jTextField1.setText(caminhoAnterior);
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + e.getMessage());
                jTextField1.setText(caminhoAnterior);
            }
        } else {
            JOptionPane.showMessageDialog(ex03, "Nenhum caminho foi selecionado!");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
        if(jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(ex03, "Escolha um arquivo de entrada!");
        }
        
        try {
            jTextArea2.setText(Ex03.processarArquivo(jTextField1.getText()));
        } catch (IOException ioe) {
            
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            Runtime.getRuntime().exec("explorer " + Paths.get("").toAbsolutePath().toString() + "\\src\\ex03\\saida.txt");
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        atualizaTAFormas();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        
        try {
            int index = Integer.valueOf(jSpinner8.getValue().toString());
            formas.remove(index);
            PersistenciaFormas.salvarFormas(formas, Paths.get("src\\ex05\\saida.txt"));
            atualizaTAFormas();
        } catch(IndexOutOfBoundsException ioobe) {
            JOptionPane.showMessageDialog(ex05, "Isira um valor de objeto válido!");
            jSpinner8.setValue(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        this.formas.add(new Circulo(Integer.valueOf(jSpinner9.getValue().toString())));
        try {
            PersistenciaFormas.salvarFormas(formas, Paths.get("src\\ex05\\saida.txt"));
        } catch(Exception e) {
            e.printStackTrace();
        }
        atualizaTAFormas();
        jSpinner9.setValue(0);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        this.formas.add(new Retangulo(Integer.valueOf(jSpinner11.getValue().toString()), Integer.valueOf(jSpinner10.getValue().toString())));
        try {
            PersistenciaFormas.salvarFormas(formas, Paths.get("src\\ex05\\saida.txt"));
        } catch(Exception e) {
            e.printStackTrace();
        }
        atualizaTAFormas();
        jSpinner11.setValue(0);
        jSpinner10.setValue(0);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        this.formas.add(new Triangulo(Integer.valueOf(jSpinner12.getValue().toString()), Integer.valueOf(jSpinner13.getValue().toString()), Integer.valueOf(jSpinner14.getValue().toString())));
        try {
            PersistenciaFormas.salvarFormas(formas, Paths.get("src\\ex05\\saida.txt"));
        } catch(Exception e) {
            e.printStackTrace();
        }
        atualizaTAFormas();
        jSpinner12.setValue(0);
        jSpinner13.setValue(0);
        jSpinner14.setValue(0);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void atualizaTAFormas() {
        try {
            formas = PersistenciaFormas.carregarFormas(Paths.get("src\\ex05\\saida.txt").toAbsolutePath());
            taFormas.setText("");
            for(int i = 0; i < formas.size(); i++) {
                taFormas.append(i + ": " + formas.get(i).getTipo() + " {"+ formas.get(i).toString() + "}\n");
            }
        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(ex05, "Erro na hora de abrir o arquivo");
        } catch (ClassNotFoundException cnfe) {
            JOptionPane.showMessageDialog(ex05, "Classe de arquivo serializado não foi encontrada");
        }
    }
    private void setTAArqEntrada() {
        if(!jTextField1.equals("")) {
            try{
                taArqEntrada.setText(Ex03.getFileString(jTextField1.getText()));
            } catch(FileNotFoundException fnfe) {
                JOptionPane.showMessageDialog(null, "Arquivo não encontrado\n" + fnfe.getMessage());
                jTextField1.setText(caminhoAnterior);
                taArqEntrada.setText("");
            } catch(IOException ioe) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro na hora de abir o arquivo\n" + ioe.getMessage());
                jTextField1.setText(caminhoAnterior);
                taArqEntrada.setText("");
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado\n" + e.getMessage());
                jTextField1.setText(caminhoAnterior);
                taArqEntrada.setText("");
            }
        } else {
            taArqEntrada.setText("");
        }
    }
    
    private void setTela(JFrame questao) {
        
        questao.setVisible(true);
        questao.setLocationRelativeTo(null);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton btnCript;
    private javax.swing.JButton btnEx01;
    private javax.swing.JButton btnEx02;
    private javax.swing.JButton btnEx3;
    private javax.swing.JButton btnEx4;
    private javax.swing.JButton btnEx5;
    private javax.swing.JFrame ex01;
    private javax.swing.JFrame ex02;
    private javax.swing.JFrame ex03;
    private javax.swing.JFrame ex04;
    private javax.swing.JFrame ex05;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner14;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea taArqEntrada;
    private javax.swing.JTextArea taFormas;
    private javax.swing.JTextField textFieldCaminho;
    private javax.swing.JFormattedTextField textFieldNumero;
    // End of variables declaration//GEN-END:variables
}
